# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\MyFiles\CondTran\demo\ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1235, 779)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(620, 540, 151, 211))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.exemplar_mode = QtWidgets.QCheckBox(self.groupBox)
        self.exemplar_mode.setGeometry(QtCore.QRect(20, 80, 111, 16))
        self.exemplar_mode.setObjectName("exemplar_mode")
        self.text_mode = QtWidgets.QCheckBox(self.groupBox)
        self.text_mode.setGeometry(QtCore.QRect(20, 100, 111, 16))
        self.text_mode.setObjectName("text_mode")
        self.stroke_mode = QtWidgets.QCheckBox(self.groupBox)
        self.stroke_mode.setGeometry(QtCore.QRect(20, 60, 101, 16))
        self.stroke_mode.setObjectName("stroke_mode")
        self.edit_input = QtWidgets.QRadioButton(self.groupBox)
        self.edit_input.setGeometry(QtCore.QRect(20, 30, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.edit_input.setFont(font)
        self.edit_input.setChecked(True)
        self.edit_input.setObjectName("edit_input")
        self.edit_output = QtWidgets.QRadioButton(self.groupBox)
        self.edit_output.setGeometry(QtCore.QRect(70, 30, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.edit_output.setFont(font)
        self.edit_output.setObjectName("edit_output")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(25, 120, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.topk = QtWidgets.QSpinBox(self.groupBox)
        self.topk.setGeometry(QtCore.QRect(50, 130, 61, 22))
        self.topk.setAlignment(QtCore.Qt.AlignCenter)
        self.topk.setMinimum(1)
        self.topk.setMaximum(4096)
        self.topk.setSingleStep(10)
        self.topk.setProperty("value", 100)
        self.topk.setObjectName("topk")
        self.sample_times = QtWidgets.QSpinBox(self.groupBox)
        self.sample_times.setGeometry(QtCore.QRect(50, 170, 41, 22))
        self.sample_times.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sample_times.setAlignment(QtCore.Qt.AlignCenter)
        self.sample_times.setMinimum(1)
        self.sample_times.setObjectName("sample_times")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 169, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(97, 169, 41, 21))
        self.label_4.setObjectName("label_4")
        self.sample_btn = QtWidgets.QPushButton(self.centralwidget)
        self.sample_btn.setGeometry(QtCore.QRect(790, 570, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.sample_btn.setFont(font)
        self.sample_btn.setObjectName("sample_btn")
        self.sampling_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.sampling_bar.setGeometry(QtCore.QRect(790, 570, 181, 41))
        self.sampling_bar.setStyleSheet("")
        self.sampling_bar.setMinimum(0)
        self.sampling_bar.setProperty("value", 100)
        self.sampling_bar.setObjectName("sampling_bar")
        self.input_group = QtWidgets.QGroupBox(self.centralwidget)
        self.input_group.setGeometry(QtCore.QRect(10, 10, 481, 521))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.input_group.setFont(font)
        self.input_group.setObjectName("input_group")
        self.input_canvas = QtWidgets.QLabel(self.input_group)
        self.input_canvas.setGeometry(QtCore.QRect(10, 30, 461, 451))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.input_canvas.setFont(font)
        self.input_canvas.setAlignment(QtCore.Qt.AlignCenter)
        self.input_canvas.setObjectName("input_canvas")
        self.input_load_btn = QtWidgets.QPushButton(self.input_group)
        self.input_load_btn.setGeometry(QtCore.QRect(180, 490, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.input_load_btn.setFont(font)
        self.input_load_btn.setObjectName("input_load_btn")
        self.input_clear_btn = QtWidgets.QPushButton(self.input_group)
        self.input_clear_btn.setGeometry(QtCore.QRect(250, 490, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.input_clear_btn.setFont(font)
        self.input_clear_btn.setObjectName("input_clear_btn")
        self.output_group = QtWidgets.QGroupBox(self.centralwidget)
        self.output_group.setGeometry(QtCore.QRect(500, 10, 481, 521))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.output_group.setFont(font)
        self.output_group.setObjectName("output_group")
        self.output_canvas = QtWidgets.QLabel(self.output_group)
        self.output_canvas.setGeometry(QtCore.QRect(10, 30, 461, 451))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.output_canvas.setFont(font)
        self.output_canvas.setAlignment(QtCore.Qt.AlignCenter)
        self.output_canvas.setObjectName("output_canvas")
        self.output_save_btn = QtWidgets.QPushButton(self.output_group)
        self.output_save_btn.setGeometry(QtCore.QRect(155, 490, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.output_save_btn.setFont(font)
        self.output_save_btn.setObjectName("output_save_btn")
        self.output_clear_btn = QtWidgets.QPushButton(self.output_group)
        self.output_clear_btn.setGeometry(QtCore.QRect(295, 490, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.output_clear_btn.setFont(font)
        self.output_clear_btn.setObjectName("output_clear_btn")
        self.output_copy_btn = QtWidgets.QPushButton(self.output_group)
        self.output_copy_btn.setGeometry(QtCore.QRect(225, 490, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.output_copy_btn.setFont(font)
        self.output_copy_btn.setObjectName("output_copy_btn")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(240, 540, 191, 211))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.exemplar_display = QtWidgets.QLabel(self.groupBox_4)
        self.exemplar_display.setEnabled(True)
        self.exemplar_display.setGeometry(QtCore.QRect(10, 60, 171, 131))
        self.exemplar_display.setText("")
        self.exemplar_display.setAlignment(QtCore.Qt.AlignCenter)
        self.exemplar_display.setObjectName("exemplar_display")
        self.load_exp_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.load_exp_btn.setGeometry(QtCore.QRect(70, 30, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.load_exp_btn.setFont(font)
        self.load_exp_btn.setObjectName("load_exp_btn")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(440, 540, 171, 211))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.text_input = QtWidgets.QTextEdit(self.groupBox_5)
        self.text_input.setEnabled(True)
        self.text_input.setGeometry(QtCore.QRect(10, 50, 151, 111))
        self.text_input.setObjectName("text_input")
        self.info = QtWidgets.QLabel(self.centralwidget)
        self.info.setGeometry(QtCore.QRect(780, 640, 201, 81))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.info.setFont(font)
        self.info.setAlignment(QtCore.Qt.AlignCenter)
        self.info.setObjectName("info")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(990, 10, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.diverse_list = QtWidgets.QListWidget(self.centralwidget)
        self.diverse_list.setGeometry(QtCore.QRect(990, 30, 231, 721))
        self.diverse_list.setObjectName("diverse_list")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1235, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setText("")
        self.action.setObjectName("action")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UniColor"))
        self.groupBox.setTitle(_translate("MainWindow", "Sampling Options"))
        self.exemplar_mode.setText(_translate("MainWindow", "From Exemplar"))
        self.text_mode.setText(_translate("MainWindow", "From Text"))
        self.stroke_mode.setText(_translate("MainWindow", "From Stroke"))
        self.edit_input.setText(_translate("MainWindow", "Gray"))
        self.edit_output.setText(_translate("MainWindow", "Color"))
        self.label.setText(_translate("MainWindow", "Top-"))
        self.label_3.setText(_translate("MainWindow", "Sample"))
        self.label_4.setText(_translate("MainWindow", "images"))
        self.sample_btn.setText(_translate("MainWindow", "Sample"))
        self.input_group.setTitle(_translate("MainWindow", "Gray"))
        self.input_canvas.setText(_translate("MainWindow", "Please load image first."))
        self.input_load_btn.setText(_translate("MainWindow", "Load"))
        self.input_clear_btn.setText(_translate("MainWindow", "Clear"))
        self.output_group.setTitle(_translate("MainWindow", "Color"))
        self.output_canvas.setText(_translate("MainWindow", "Please load image first."))
        self.output_save_btn.setText(_translate("MainWindow", "Save"))
        self.output_clear_btn.setText(_translate("MainWindow", "Clear"))
        self.output_copy_btn.setText(_translate("MainWindow", "Copy"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Exemplar"))
        self.load_exp_btn.setText(_translate("MainWindow", "Load"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Text"))
        self.info.setText(_translate("MainWindow", "Welcome"))
        self.label_2.setText(_translate("MainWindow", "Results"))

